### ISSUE TITLE
Incorrect link to go-yaml

### ISSUE THREAD

**Issue by cbandy** [yaml/yaml-runtimes#20]
The test is importing `gopkg.in/yaml.v2` which is hosted at https://github.com/go-yaml/yaml, but the README links to a different project, https://github.com/goccy/go-yaml.

- https://github.com/go-yaml/yaml#installation-and-usage
  > To install it, run:
  > ```
  > go get gopkg.in/yaml.v2
  > ```

- https://github.com/goccy/go-yaml#installation
  > ```
  > go get -u github.com/goccy/go-yaml
  > ```

https://github.com/yaml/yaml-runtimes/blob/d3eeec97c1f0e99cfdfd70d81743f46b24b2b3bd/docker/static/utils/go-yaml-json.go#L6

https://github.com/yaml/yaml-runtimes/blob/d3eeec97c1f0e99cfdfd70d81743f46b24b2b3bd/list.yaml#L72

**Comment by perlpunk** [comment]
Thanks! updated the link
