### ISSUE TITLE
The YAML feature added, now Java is complete:    ` tests: [event, json, yaml]`

### ISSUE THREAD

**Issue by moovy2** [yaml/yaml-runtimes#24]
The YAML feature added, now Java is complete:    ` tests: [event, json, yaml]`

```
$ docker run -i --rm yamlio/alpine-runtime-java java-snakeyaml-yaml <t/data/input.yaml
%TAG ! !
%TAG !! tag:yaml.org,2002:
---
foo: bar
```

_Originally posted by @asomov in https://github.com/yaml/yaml-runtimes/issues/23#issuecomment-1002481923_

**Comment by moovy2** [comment]
> 

> 

- [ ]

**Comment by asomov** [comment]
@moovy2 what is the issue ?

**Comment by perlpunk** [comment]
script kiddie testing their new bot?
