### ISSUE TITLE
Rebase & squash vs merge

### ISSUE THREAD

**Issue by asomov** [yaml/yaml-runtimes#27]
I have read the [wiki with instruction Git Practices ](https://github.com/yaml/yaml-runtimes/blob/master/Contributing.md)
I have recently contributed the SnakeYAML integration and this is what I see now when I compare the branches:
![compare-branches-yaml](https://user-images.githubusercontent.com/1632547/151962582-1a970a3f-759e-47f2-a0c5-38fa25b8279c.png)

Please observe the following:

1. it looks like my commits are not present in master
2. the commits are squashed into one

I created 3 commits because they are different in nature. Code formatting should never be mixed with any other changes.
Now all the changes a re mixed making it difficult to see the real changes. 
Rebase and squash do not encourage the team work. Would you consider to apply normal merging strategy ?
What is the real reason to have flat history ? What do you solve  ?

**Comment by perlpunk** [comment]
Rebasing has several advantages:
* the code should ideally be tested based on master. if the code is not based on master and gets merged, it might break.
* I find it easier to follow a history that is either flat, or in case of more commits per PR, the branches are all based on the current main branch at that time.

I would have tried to rebase your PR myself before merging a merge commit, but you didn't check the box that would have allowed my to push to your PR branch, so for simplicity I decided to squash the commits.
I do see value in keeping several commits in some cases but didn't see it as that important in this case.
So if you check the box in the future to allow me to rebase your branch, I will try to keep seperate commits where it makes sense :)

**Comment by asomov** [comment]
The first statement is confusing. The test must NOT be executed per branch but per every commit. My proposal is that when my code is added to the master branch we use fast-forward WITHOUT any merge at all ! I do not like to add artificial merge commit just to indicate the merge and I do not propose it
I do not get the second statement - sorry.
My proposal - the developer makes a PR and it is added to master AS IS (no rebase, no squash, no additional merge commit)

**Comment by ingydotnet** [comment]
@asomov The policies and decisions of how to organize and maintain a project belong to the project owners.

For most of the repositories in the https://github.com/yaml organization, we have chosen to keep a flat history and sometimes squash or amend commits as we deem appropriate.

**Comment by asomov** [comment]
@ingydotnet everyone is allowed to make a mistake. No problem with that. If it is not a mistake you can explain and justify it. If something was appropriate 10 years ago it does not mean it is appropriate now.
I explain myself - you do not. If you keep rejecting every proposal without any valid explanation (and the community will support such an approach) I will get it as a very explicit signal.

**Comment by perlpunk** [comment]
> The first statement is confusing. The test must NOT be executed per branch but per every commit.

I don't understand what you're saying here with regard to my statement.
A branch that is based on an older commit should be rebased first if there were changes in master in the meantime, to make sure that the branch still works. That's why I like to rebase.

> My proposal is that when my code is added to the master branch we use fast-forward WITHOUT any merge at all !

Excuse me, but that is not always possible, if other changes get merged in the meantime.
If you rebase yourself in that case, or let me do it, fine.
And I don't want to use a fast-forward merge in every case, because a merge commit can make sense for PRs with more than one commit. They show as related, and the whole merge commit can be reverted in one step if necessary.

> I do not get the second statement - sorry.

I find the git history easier to read if
* the history is flat
* or in case of more commits per PR, every PR branch base starts at the latest master commit

> My proposal - the developer makes a PR and it is added to master AS IS (no rebase, no squash, no additional merge commit)

That's impossible. As soon as there is a newer commit in master, at least one of those three things have to happen, and a fast forward merge is not possible anymore.

**Comment by perlpunk** [comment]
> If you keep rejecting every proposal without any valid explanation (and the community supports such an approach) I will get it as a very explicit signal.

Can you please stop making claims like that and act like you are the only one who knows how to manage a git repository, and everyone has to follow your rules?

I did politely answer your question, and your reaction in this thread is not friendly.

We welcome any contributor to the YAML project, as there is a lot of work, but currently your producing more work than solving anything.

 I will lock this thread now.
